import type { Metadata } from "next";
import { Roboto_Condensed, Inter } from "next/font/google";
import "./globals.css";

export const robotoCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["700"], // bold for headings
});

export const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600"], // for body + subheading
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${robotoCondensed.className}`}>
        {children}
      </body>
    </html>
  );
}
